/**
 * Client for the City Shield API.
 *
 * The app must keep working when the API is unreachable - a backend outage is
 * not a reason a person in danger loses the SOS button. Every call therefore
 * reports failure rather than throwing into the render tree, and the caller
 * decides how to degrade.
 */

const BASE = import.meta.env.VITE_API_URL || 'http://localhost:8787';

const newKey = () =>
  crypto.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`;

async function request(path, { method = 'GET', body, idempotencyKey, signal } = {}) {
  const headers = { accept: 'application/json' };
  if (body) headers['content-type'] = 'application/json';
  if (idempotencyKey) headers['idempotency-key'] = idempotencyKey;

  const res = await fetch(`${BASE}${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
    signal,
  });

  const text = await res.text();
  const data = text ? JSON.parse(text) : null;
  if (!res.ok) {
    const err = new Error(data?.error ?? `Request failed: ${res.status}`);
    err.status = res.status;
    err.issues = data?.issues;
    throw err;
  }
  return data;
}

export const api = {
  base: BASE,

  health: (signal) => request('/health', { signal }),

  /**
   * Raise an incident.
   *
   * The idempotency key is generated by the CALLER and reused across retries.
   * Someone tapping SOS on a failing connection will tap again; without this,
   * each tap becomes its own separate emergency.
   */
  createIncident: (input, idempotencyKey = newKey()) =>
    request('/v1/incidents', { method: 'POST', body: input, idempotencyKey }),

  getIncident: (id, signal) => request(`/v1/incidents/${id}`, { signal }),

  addPing: (id, ping) =>
    request(`/v1/incidents/${id}/pings`, { method: 'POST', body: ping }),

  reverseGeocode: ({ lat, lng }, signal) =>
    request(`/v1/geo/reverse?lat=${lat.toFixed(6)}&lng=${lng.toFixed(6)}`, { signal }),

  /** SSE URL. EventSource handles its own reconnection, so we hand back the URL. */
  streamUrl: (id) => `${BASE}/v1/incidents/${id}/stream`,

  newKey,
};

/**
 * Is the API reachable? Resolved once at startup and surfaced in the UI, so the
 * app can say it is running on local data instead of silently pretending.
 */
export async function probeApi(timeoutMs = 2500) {
  const ctl = new AbortController();
  const t = setTimeout(() => ctl.abort(), timeoutMs);
  try {
    const h = await api.health(ctl.signal);
    return { online: true, capabilities: h.capabilities };
  } catch {
    return { online: false, capabilities: null };
  } finally {
    clearTimeout(t);
  }
}
